/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        bg: 'var(--bg)',
        surface: 'var(--surface)',
        'surface-2': 'var(--surface-2)',
        line: 'var(--line)',
        'line-soft': 'var(--line-soft)',
        ink: 'var(--ink)',
        dim: 'var(--dim)',
        faint: 'var(--faint)',
        text: 'var(--text)',
        'text-dim': 'var(--text-dim)',
        'text-faint': 'var(--text-faint)',
        brand: 'var(--brand)',
        'brand-soft': 'var(--brand-soft)',
        'brand-deep': 'var(--brand-deep)',
        critical: 'var(--critical)',
        'critical-soft': 'var(--critical-soft)',
        caution: 'var(--caution)',
        'caution-soft': 'var(--caution-soft)',
        good: 'var(--good)',
        'good-soft': 'var(--good-soft)',
        ready: 'var(--ready)',
        'ready-soft': 'var(--ready-soft)',
        'sig-critical': 'var(--sig-critical)',
        'sig-caution': 'var(--sig-caution)',
        'sig-good': 'var(--sig-good)',
        purple: 'var(--purple)',
        'purple-soft': 'var(--purple-soft)',
        'brand-glow': 'var(--brand-glow)',
        sidebar: 'var(--sidebar-bg)',
        'sidebar-surface': 'var(--sidebar-surface)',
        'sidebar-text': 'var(--sidebar-text)',
        'sidebar-muted': 'var(--sidebar-muted)',
        'sidebar-inactive': 'var(--sidebar-inactive)',
        'sidebar-line': 'var(--sidebar-line)',
      },
      fontFamily: {
        display: ['"Space Grotesk"', 'system-ui', 'sans-serif'],
        body: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'ui-monospace', 'monospace'],
      },
      borderRadius: {
        card: '16px',
        panel: '22px',
      },
      boxShadow: {
        panel: 'var(--shadow-lg)',
        card: 'var(--shadow)',
      },
    },
  },
  plugins: [],
};
